apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-demo
  labels:
    app: ai-demo
    env: qa
  annotations:
    dev.nocalhost: |-
      name: nocalhost-api
      serviceType: deployment
      containers:
        - name: nocalhost-api
          dev:
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-demo
  template:
    metadata:
      labels:
        app: ai-demo
        env: qa
    spec:
      containers:
        - image: ghcr.io/hongchaodeng/ai-demo:latest
          name: my-kube-api
          command: ["python3", "api.py" ]
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"