name: ai-demo

build:
  build-image:
    stack: docker
    parameters:
      image: ghcr.io/hongchaodeng/ai-demo

deploy:
  train-model:
    stack: batch-job
    parameters:
      container:
        image: $(build.build-image.outputs.image)
        cmd:
          - python3
          - train.py

  serve-model:
    stack: web-api
    dependsOn:
      - train-model
    parameters:
      container:
        image: $(build.build-image.outputs.image)
        cmd:
          - python3
          - api.py
