name: ai-demo

build:
  scipy:
    stack: scipy-builder
    parameters:
      image: ghcr.io/hongchaodeng/ai-demo:latest
      pre-build:
        - mkdir my-model
      env:
        - MODEL_DIR=${WORKSPACE}/my-model
        - MODEL_FILE_LDA=clf_lda.joblib
        - MODEL_FILE_NN=clf_nn.joblib

deploy:
  train-model:
    stack: batch-job
    parameters:
      cmd:
        - python3
        - train.py

  serve-model:
    stack: online-service
    dependsOn:
      - train-model
    parameters:
      cmd:
        - python3
        - api.py
