name: ai-demo

train-model:
  container:
    image: ghcr.io/hongchaodeng/ai-demo
    cmd:
      - python3
      - train.py
  backoffLimit: 4

serve-model:
  container:
    image: ghcr.io/hongchaodeng/ai-demo
    cmd:
      - python3
      - api.py
  autoscaling:
    min: 1
    max: 3
  monitoring:
    groups:
      - name: example
        rules:
          - alert: APIHighRequestLatency
            expr: api_http_request_latencies_second{quantile="0.5"} > 1
            for: 10m
            annotations:
              summary: "High request latency on {{ $labels.instance }}"
              description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"

#TrainModel
#ServeModel
#Container
#Autoscaling
#Monitoring
