metadata:
  name: ai-demo
  namespace: default

# build:
#   source: ./
#   push:
#     target: ghcr.io/hongchaodeng/ai-demo

trainModel:
  container:
    image: ghcr.io/hongchaodeng/ai-demo
    cmd:
      - python3
      - train.py
  backoffLimit: 4

serveModel:
  env: qa
  container:
    image: ghcr.io/hongchaodeng/ai-demo
    cmd:
      - python3
      - api.py
    port: 5000
  autoscaling:
    min: 1
    max: 3
  monitoring:
    groups:
      - name: example
        rules:
          - alert: APIHighRequestLatency
            expr: api_http_request_latencies_second{quantile="0.5"} > 1
            for: 10m
            annotations:
              summary: "High request latency on {{ $labels.instance }}"
              description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"

